universal parsing now integrated into EKR
sambanova/ai-starter-kit pull request #122
Opened 2024-05-21 14:53 UTC by snova-kwasia

2024-05-23 13:15 UTC, snova-jorgep commented
@snova-kwasia  for universal parsing in EKR, everything looks, tested, and is working well, we need to update the EKR readme  to include instructions to launch the universal parser docker container, or alternatively local env installation

2024-06-05 16:15 UTC, snova-jorgep requested changes

2024-06-05 16:15 UTC, snova-jorgep commented on utils/eval/rag_eval.py
> +from langchain_community.llms.sambanova import SambaStudio, Sambaverse
those looks like are not being used, where are the models being instanced?

2024-06-05 16:15 UTC, snova-jorgep commented on eval_jumpstart/README.md
> +These are from RAGAS please see the RAGAS website for details on the underlying methodlogy
typo in methodology

2024-06-05 16:15 UTC, snova-jorgep commented on eval_jumpstart/README.md
> +# Evaluation Use Cases
Think Worth it to include a short explanation of each use case

2024-06-05 16:15 UTC, snova-jorgep commented on utils/eval/config.yaml
> +  #context_col: contexts
why is this commented, saw streamlit app requires it

2024-06-05 16:15 UTC, snova-jorgep commented on utils/eval/app.py
Should we include the st app usage in the readme?

2024-06-19 15:45 UTC, snova-kwasia commented on enterprise_knowledge_retriever/src/document_retrieval.py
>          """Extract text and metadata from pdf document with pypdf2 loader
fixed

2024-06-19 15:45 UTC, snova-kwasia commented on utils/parsing/README.md
fixed

2024-06-19 15:55 UTC, snova-kwasia commented on utils/parsing/README.md
>     pip install git+https://github.com/sambanova/ai-starter-kit
WIll update the reqs.

2024-06-19 15:57 UTC, snova-kwasia commented on utils/parsing/docker-compose.yml
> +      - ./.env
updated

2024-06-19 16:00 UTC, snova-kwasia commented on enterprise_knowledge_retriever/streamlit/app.py
> +                    #text_chunks = documentRetrieval.get_text_chunks_with_metadata(docs=raw_text, meta_data=meta_data)
done

2024-06-20 18:40 UTC, snova-jorgep approved these changes

2024-06-20 19:29 UTC, merged