data extraction kit update
sambanova/ai-starter-kit pull request #201
Opened 2024-07-15 22:32 UTC by snova-luiss

Update langchain versions requirement files
Update HuggingFaceEmbeddings from langchain community docker files

2024-07-19 20:41 UTC, snova-jorgep requested changes
minor change requested

2024-07-19 20:41 UTC, snova-jorgep commented on data_extraction/notebooks/retrieval_from_pdf_tables.ipynb
> +    "    model_kwargs={\"do_sample\": False, \"temperature\": 0.0, \"select_expert\": \"llama-2-7b-chat-hf\"},\n",
here please add a comment that indicates select expert should be removed if not using CoE

2024-07-19 22:35 UTC, snova-jorgep approved these changes

2024-07-25 14:47 UTC, snova-jorgep commented
@snova-kwasia already reviewed by me, can we merge this PR

2024-07-29 23:11 UTC, snova-kwasia commented
Thanks @snova-luiss great work. Merged.

2024-07-29 23:11 UTC, merged