PCA unit test
sambanova/ai-starter-kit pull request #204
Opened 2024-07-17 23:47 UTC by snova-petrojm

2024-07-24 11:00 UTC, snova-kwasia requested changes
Great work @snova-petrojm ! My change is super minor around maintainability.

2024-07-25 01:41 UTC, snova-petrojm commented on post_call_analysis/config.yaml
> +    "coe": False #set true if using Sambastudio embeddings in a CoE endpoint
done, thanks

2024-07-25 01:41 UTC, snova-petrojm commented on post_call_analysis/tests/pca_test.py
> +audio_save_location=(os.path.join(kit_dir,"data/conversations/audio"))
done, thanks

2024-07-25 13:53 UTC, snova-jorgep approved these changes

2024-07-25 13:59 UTC, snova-kwasia commented
Looks good thanks @snova-petrojm!

2024-07-25 14:00 UTC, merged