Handler errors and empty results
sambanova/ai-starter-kit pull request #216
Opened 2024-07-26 20:08 UTC by snova-luiss

2024-07-29 22:00 UTC, snova-jorgep requested changes
some minor cahnges

2024-07-29 22:00 UTC, snova-jorgep commented on search_assistant/src/search_assistant.py
> +            results = response.get('organic_results', None)
results = response.get('organic_results', None) -> results = response.get('organic_results', [])

2024-07-30 17:58 UTC, snova-jorgep approved these changes
Thanks everything looking good, approved

2024-07-30 18:49 UTC, merged

2024-07-30 18:49 UTC, snova-kwasia commented
Merged thanks @snova-luiss