Implementation of synthetic table data
sambanova/ai-starter-kit pull request #310
Opened 2024-09-11 16:51 UTC by snova-codym

This update will:

- Allow for the generation of synthetic table images from modified tsv formatted tables.
- Create qa pairs for table qa.
- Create ocr prompts and completions.

More functionality will likely need to be extended, such as more control over image augmentations.

2024-09-13 12:58 UTC, snova-codym commented on yoda/llava_data_prep/src/table_utils.py
> +class QAItem(BaseModel):
@snova-francescar

2024-09-15 03:24 UTC, snova-kwasia requested changes
Have given a first pass at this and added a few comments, they aren't major changes. Additionally can you add a README.md? This is required for any new kit.

2024-09-15 03:24 UTC, snova-kwasia commented on utils/sec_utilities/edgar_ingestion.py
> +import yaml
Can we please move this to a utils within the yoda  kit repo? This isn't a multi kit util.

2024-09-15 03:24 UTC, snova-kwasia commented on yoda/llava_data_prep/config.yaml
> +    "select_expert": "Meta-Llama-3.1-70B-Instruct" #set if using sncloud, SambaStudio CoE llm expert
Let's please remove the if using sncloud here, as this is a SambaStudio only kit as far as I'm aware.

2024-09-15 03:24 UTC, snova-kwasia commented on yoda/llava_data_prep/scripts/create_synthetic_tables.py
> +    print(LOGS_PATH)
Please remove print here or turn to logging.info if it's needed.

2024-09-15 03:24 UTC, snova-kwasia commented on yoda/llava_data_prep/src/generate_tables.py
> +columns: str = "\\begin{tabular}{| l c c r c c r |}\n\\hline\n"
Should these 2 literal strings perhaps be in a config somewhere? I assume they change with different types of table to be generated?

2024-09-15 03:24 UTC, snova-kwasia commented on yoda/llava_data_prep/table_templates/sec_edgar/AAPL.py
> +synth_tables = []
Similar comment to above. Could these live in a json file for the given company in this case Apple? That way they can be pulled in when necessary?

2024-09-15 03:24 UTC, snova-kwasia commented on yoda/llava_data_prep/table_templates/sec_edgar/AAPL.py
> +ex1 = {"columns": "\\begin{tabular}{| l c c |}\n\\hline\n",
Could you please make these variable names more descriptive? Not sure what ext1 etc means.

2024-09-19 21:26 UTC, snova-luiss commented
Minor suggestions:
- Make sure to add output files to the .gitignore (images, json, sec_data, pt, aux, etc)
- Add system dependencies to the readme

2024-09-19 21:31 UTC, snova-codym commented
@snova-luiss Thanks - I will do both of these things tomorrow AM.

2024-09-20 13:37 UTC, snova-kwasia requested changes
Minor changes.

2024-09-20 13:37 UTC, snova-kwasia commented on yoda/llava_data_prep/requirements.txt
> +aiohappyeyeballs==2.4.0
Is this a pip freeze or the actual requirements (longer than our base-requirements.txt!)? If possible let's just add the requirements for the kit.

2024-09-20 13:37 UTC, snova-kwasia commented on yoda/llava_data_prep/README.md
> +and ensure yoda/llava_data_prep/test is created with a subfolder of synthetic images and yoda/llava_data_prep/test/annotations_train.json exists.
Might want to change the language here to - "After completion yoda/llava_data_prep/test is created ....etc"
Currently I read this as something the user needs to ensure vs the output of the previous command.

2024-09-24 13:37 UTC, snova-luiss commented
The images and the JSON file (annotations_train.json) should also be added to the .gitignore. Other than that, looks good to me!

2024-09-24 13:49 UTC, snova-luiss approved these changes
lgtm!

2024-09-24 14:09 UTC, snova-kwasia approved these changes
LGTM @snova-codym

2024-09-24 14:09 UTC, merged