Improvement: Bundle update
sambanova/ai-starter-kit pull request #425
Opened 2024-10-28 23:14 UTC by snova-luiss

2024-11-11 15:06 UTC, snova-jorgep requested changes
fix typo (minor)

2024-11-11 15:06 UTC, snova-rodrigom requested changes
LGTM, dropped a small comment and could you confirm if the kits impacted have been tested?

2024-11-11 15:06 UTC, snova-rodrigom commented on bundle_jump_start/README.md
> +      "bundle": True #set as true if using Sambastudio CoE endpoint
Please change this CoE reference and check if there are others.

2024-11-11 17:08 UTC, snova-jorgep approved these changes

2024-11-12 14:56 UTC, snova-rodrigom approved these changes
LGTM now, thanks @snova-luiss

2024-11-18 19:05 UTC, merged